### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by FerDR89** [gonzaliski/desafio-m7#1]
Buenas, felicitaciones por llegar a esta instancia.

Te dejo algunas cosas que vi por corregir:

Cuando cierra sesión me redirige a una page que no existe

![image](https://user-images.githubusercontent.com/74626765/185415986-7831cac2-7352-4bce-a8c1-b0d85b481bfe.png)

No me funcionó el modificar la contraseña. Le pase solo la contraseña, solo el nombre o el nombre + contraseña y nada. El request a ese endpoint me devuelve un objeto vacio.

El update de la mascota solo me funciono el cambio de nombre, el cambio de ubicación e imagen no lo estaría tomando:

![image](https://user-images.githubusercontent.com/74626765/185418694-a3115282-cdaf-4da7-ba4f-b1f026dc2475.png)

Extras que no hacen al desafío como tal pero creo que pueden ser mejoras para dejarlo sobresaliente:

Este comp estaría buenísimo que si no hay nadie logeado no se muestre (consultando el state es un toque):
![image](https://user-images.githubusercontent.com/74626765/185416438-66339eaf-998a-4bd2-b267-97b563da88c4.png)

Te lo paso a necesita ajuste para que puedas corregir los primeros puntos y volvé a enviarlo por favor.
Cualquier duda que tengas porfa dejala en Discord así podemos darte una mano

**Comment by gonzaliski** [comment]
Buenas Fer! Gracias por las indicaciones, ya estan pusheadas y deployeando!
